urls <- c(Sopron = "https://odp.met.hu/climate/homogenized_data/station_data_series/from_1870/precipitation_sum/r_h_Sopron_18702025.csv.zip")
zipfilename <- paste0(names(urls)[urlnr], ".zip")
download.file(urls[urlnr], zipfilename, mode = "wb")
csvfile <- unzip(zipfilename, list = TRUE)$Name
unzip(zipfilename, exdir = tempdir())
adat <- read.table(file.path(tempdir(), csvfile), sep = ";", head = TRUE)
urls <- c(Sopron_akt = "https://odp.met.hu/climate/observations_hungary/daily_rain/recent/HABP_1RD_13713_akt.zip")
zipfilename <- paste0(names(urls)[urlnr], ".zip")
download.file(urls[urlnr], zipfilename, mode = "wb")
csvfile <- unzip(zipfilename, list = TRUE)$Name
unzip(zipfilename, exdir = tempdir())
adat_akt <- read.table(file.path(tempdir(), csvfile), sep = ";", head = TRUE)
finalobjectname <- paste0("P", adat[1, "StationNumber"], ".xts")
assign(finalobjectname, xts(c(adat$r,adat_akt$r) ,as.Date(as.character(c(adat$Time,adat_akt$Time)), format = "%Y%m%d")))
annual_hydro <- HydYearUntilNow(P.xts, "10-31")
barplot(zoo(annual_hydro$V1, annual_hydro[,"HY"]), main = "Sopron", col = "lightblue", xaxs = "i")
